apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}