deployment:
  myApp:
    image:
      repository: 211125355004.dkr.ecr.us-east-1.amazonaws.com/my-app
      tag: latest
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
