apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: eu-west-1-ecr-registry
      containers:
        - name: nestjs-container
          image: 051826725870.dkr.ecr.eu-west-1.amazonaws.com/nestjs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

kubernetesClusterDomain: cluster.local

service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 32001
  type: NodePort