deployment:
  myApp:
    image:
      repository: 051826725870.dkr.ecr.eu-west-1.amazonaws.com/nestjs
      pullPolicy: Always
      tag: latest
    imageCredentials:
      registry: 051826725870.dkr.ecr.eu-west-1.amazonaws.com
      username: AWS
      # The password should be the output of: aws ecr get-login-password --region eu-west-1
      password: ""
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
