deployment:
  myApp:
    image:
      repository: 051826725870.dkr.ecr.eu-west-1.amazonaws.com/nestjs
      pullPolicy: Always
      tag: latest
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
