deployment:
  myApp:
    image:
      repository: 051826725870.dkr.ecr.eu-west-1.amazonaws.com/nestjs
      pullPolicy: Always
      tag: latest
    imagePullSecrets:
    - name: eu-west-1-ecr-registry
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 32001
  type: NodePort