deployment:
  myApp:
    image:
      repository: public.ecr.aws/b8e7o6b4/rolling/app
      pullPolicy: Always
      tag: latest
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer