apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-deployment
  labels:
  {{- include "my-chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: my-app
    {{- include "my-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: my-app
      {{- include "my-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.myApp.image.repository }}:{{ .Values.deployment.myApp.image.tag
          | default .Chart.AppVersion }}
        name: my-app
        ports:
        - containerPort: 80
        resources: {}