apiVersion: v1
kind: Pod                                            
metadata:
  name: my-app   
  labels:
    app: my-app                              
spec:                                                
  containers:
    - image: 051826725870.dkr.ecr.eu-west-1.amazonaws.com/nestjs
      name: -cntnr                            
      ports:
        - containerPort: 8080    
  imagePullSecrets:
  - name: eu-west-1-ecr-registry